"""Capability identifiers used by policy and plugin boundaries."""

from enum import StrEnum


class Capability(StrEnum):
    READ_MARKET_DATA = "READ_MARKET_DATA"
    READ_FUNDS = "READ_FUNDS"
    READ_POSITIONS = "READ_POSITIONS"
    CREATE_PAPER_ORDER = "CREATE_PAPER_ORDER"
    CREATE_LIVE_ORDER = "CREATE_LIVE_ORDER"
    CANCEL_ORDER = "CANCEL_ORDER"
    START_STRATEGY = "START_STRATEGY"
    STOP_STRATEGY = "STOP_STRATEGY"
    ACCESS_BROKER = "ACCESS_BROKER"
    ACCESS_SECRETS = "ACCESS_SECRETS"
    EXECUTE_LIVE = "EXECUTE_LIVE"
